version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/[닉네임]-[gridge-test-id]
    overwrite: yes
permissions:
  - object: /var/www/html/
    owner: root
    group: root
    mode: 755
